# Generated by Django 5.2.4 on 2026-09-24 03:23

import projects.models
import projects.validators
from django.db import migrations, models


def assign_neutral_slugs(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    for project in Project.objects.using(schema_editor.connection.alias).all().iterator():
        project.slug = f"project-{project.pk}"
        project.save(using=schema_editor.connection.alias, update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_pricing_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectimage", name="image",
            field=models.ImageField(upload_to=projects.models.project_image_upload_to, validators=[projects.validators.validate_project_image]),
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AddField(
            model_name="project",
            name="featured_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Order within featured placement; lower first."
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="featured_placement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Archive"),
                    ("lead", "Lead evidence"),
                    ("supporting", "Supporting evidence"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="headline",
            field=models.TextField(
                blank=True,
                help_text="Optional editorial headline; line breaks are supported by the public presentation.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="project", name="slug",
            field=models.SlugField(max_length=120, null=True),
        ),
        migrations.RunPython(assign_neutral_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="project", name="slug",
            field=models.SlugField(default=projects.models.new_project_slug, help_text="Stable public identity. Assign renter only after confirming the record.", max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                blank=True,
                help_text="Verified public project status, or leave blank.",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("featured_placement", "lead"), ("is_published", True)
                ),
                fields=("featured_placement",),
                name="one_lead_project_placement",
            ),
        ),
    ]
