import { ClosingAction, PageLead, SignalLink } from "./SiteShell.jsx";
const steps=[
 ["Frame the problem","Start with the people, the workflow, and what must be true. Identify the exception paths before they become production surprises.","Actors / constraints / outcomes"],
 ["Make the system decision","Choose boundaries, data ownership, and control surfaces. Record the trade-off and the condition that would change the decision.","Architecture / responsibility / trade-offs"],
 ["Build both sides","Develop the customer experience alongside the controls needed to run it. Review working slices of the product as the system takes shape.","Interface / operations / feedback"],
 ["Prepare for production","Check access, visibility, recovery, and release paths. Agree on what the handover and ongoing operation need to include.","Release / recovery / ownership"],
];
export default function ApproachPage(){return <>
  <PageLead index="04 / Approach" title={<>From problem.<br /><em>To production.</em></>} intro="RACCN works across product design and implementation, with the operational side considered from the beginning." />
  <section className="site-approach-scope site-section" id="scope"><span className="site-label">Scope / What needs to work</span><h2>Digital products<br />with more than<br />one side.</h2><div>{[["Product interfaces","Marketplaces, commerce, directories, SaaS, and AI-enabled workflows."],["Operational software","Admin surfaces, internal tools, permissions, and exception handling."],["Connected systems","APIs, integrations, data models, and the logic between interfaces."]].map(([title,body])=><article key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></section>
  <section className="site-section site-approach-sequence" id="working-together"><header><span className="site-label">Working together / A connected sequence</span><h2>Make the work<br />understandable.</h2></header><div>{steps.map(([title,body,note],i)=><article key={title} data-resolve><span className="site-sequence-number">0{i+1}</span><h3>{title}</h3><p>{body}</p><small>{note}</small></article>)}</div></section>
  <section className="site-editorial site-section" id="engineering" data-resolve><span className="site-label">Engineering / Fit before fashion</span><h2>The stack follows<br />the constraints.</h2><div><p>Choose tools for the product’s workload, the team maintaining it, and the cost of changing it. Clear boundaries and recoverable operations matter more than a long technology list.</p><SignalLink to="/systems/decisions">See how decisions are made</SignalLink></div></section>
  <section className="site-editorial site-section" id="practice" data-resolve><span className="site-label">Practice / RACCN Code</span><h2>Think beyond<br />the visible surface.</h2><div><p>The distinguishing question is what happens after the main customer flow: who can correct a record, resolve an exception, understand a failure, or safely change a rule?</p><p>Those questions shape the product alongside its visual design.</p></div></section>
  <section className="site-approach-fit site-section" id="fit"><div><span className="site-label">Fit / A useful starting point</span><h2>Bring the problem.<br />Leave room to solve it.</h2><p>A clear decision owner, access to the relevant workflow, and room to discuss trade-offs make the work more productive.</p></div><div id="engagement"><span className="site-label">Engagement / Define the next useful step</span><p>You do not need a finished specification to start. Share what you are building or changing. We can discuss the scope, constraints, responsibilities, and a practical next step before a delivery commitment.</p><SignalLink to="/start/define">Explore an indicative scope</SignalLink></div></section>
  <ClosingAction title={<>What are you<br />trying to make work?</>} />
</>}
