import { useEffect, useRef, useState } from "react";
import { ChoiceGroup, SignalLink } from "./SiteShell.jsx";
import { VIEW_OPTIONS, ADMIN_NAV, KPI_DATA, USERS_SEED, PERMISSION_OPTIONS, PIPELINE_COLUMNS, PIPELINE_SEED, TRANSACTIONS_SEED, DISPUTES_SEED, SETTINGS_SEED, AUDIT_LOG, CUSTOMER_ORDERS, CUSTOMER_NOTIFICATIONS } from "./demoData.js";
const money = value => Number(String(value).replace(/[$,]/g,""));
const format = value => new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(value);
export default function DemoPage() {
  const [view,setView]=useState("admin");const [section,setSection]=useState("dashboard");
  const [users,setUsers]=useState(USERS_SEED);const [userId,setUserId]=useState(USERS_SEED[0].id);
  const [pipeline,setPipeline]=useState(PIPELINE_SEED);const [transaction,setTransaction]=useState(null);
  const [disputeId,setDisputeId]=useState(DISPUTES_SEED[0].id);const [announcement,setAnnouncement]=useState("");
  const dialog=useRef(null);const user=users.find(x=>x.id===userId);const dispute=DISPUTES_SEED.find(x=>x.id===disputeId);
  useEffect(()=>{if(transaction){dialog.current?.showModal();}else{dialog.current?.close();}},[transaction]);
  const move=(id,status)=>{if(!PIPELINE_COLUMNS.some(x=>x.id===status))return;setPipeline(cards=>cards.map(card=>card.id===id?{...card,status}:card));setAnnouncement(`Item moved to ${PIPELINE_COLUMNS.find(x=>x.id===status).label}.`);};
  const toggle=(permission)=>setUsers(current=>current.map(x=>x.id!==userId?x:{...x,permissions:x.permissions.includes(permission)?x.permissions.filter(p=>p!==permission):[...x.permissions,permission]}));
  return <section className="site-demo">
    <header className="site-demo-header"><div><span className="site-label">Systems / Operational demo</span><h1>Control in practice.</h1><p>Fictional simulation. Changes stay in this tab and reset when you leave.</p></div><ChoiceGroup legend="Workspace" name="demo-view" options={VIEW_OPTIONS} value={view} onChange={setView}/></header>
    <p className="site-sr-only" role="status">{announcement}</p>
    {view==="admin" ? <div className="site-demo-layout"><nav aria-label="Demo workspace">{ADMIN_NAV.map(item=><button key={item.id} aria-pressed={section===item.id} onClick={()=>setSection(item.id)}>{item.label}<span aria-hidden="true">↗</span></button>)}</nav><div className="site-demo-workspace"><header><span className="site-label">Admin / {String(ADMIN_NAV.findIndex(x=>x.id===section)+1).padStart(2,"0")}</span><h2>{ADMIN_NAV.find(x=>x.id===section).label}</h2><p>{ADMIN_NAV.find(x=>x.id===section).summary}</p></header>
      {section==="dashboard" && <><div className="site-demo-metrics">{KPI_DATA.map(kpi=><div key={kpi.id}><span>{kpi.label}</span><strong>{kpi.value}</strong><small>{kpi.trend.value} / fictional data</small></div>)}</div><div className="site-demo-columns"><section><h3>Operations watchlist</h3><ul className="site-demo-list"><li>Identity reviews <span>12 pending</span></li><li>Payout approvals <span>4 waiting</span></li><li>Dispute evidence <span>2 high risk</span></li></ul></section><section><h3>Decisions waiting</h3><p>Revenue variance in the EU region.</p><p>Northwind Co chargeback review.</p><p>Support backlog above the sample threshold.</p></section></div></>}
      {section==="users" && <div className="site-demo-columns"><section><h3>Operators</h3><div className="site-demo-select-list">{users.map(x=><button key={x.id} aria-pressed={userId===x.id} onClick={()=>setUserId(x.id)}><strong>{x.name}</strong><small>{x.email}</small><span>{x.role}</span></button>)}</div></section><section><h3>{user.name}</h3><p className="site-caption">Permission controls / {user.role}</p><div className="site-demo-permissions">{PERMISSION_OPTIONS.map(permission=><label key={permission}><input type="checkbox" checked={user.permissions.includes(permission)} onChange={()=>toggle(permission)}/><span>{permission}</span></label>)}</div></section></div>}
      {section==="pipelines" && <><p className="site-caption">Move an item with its stage selector, or drag it to another column.</p><div className="site-demo-pipeline">{PIPELINE_COLUMNS.map(column=><section key={column.id} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();move(event.dataTransfer.getData("text/plain"),column.id);}}><h3>{column.label}<span>{pipeline.filter(x=>x.status===column.id).length}</span></h3>{pipeline.filter(x=>x.status===column.id).map(card=><article key={card.id} draggable onDragStart={event=>event.dataTransfer.setData("text/plain",card.id)}><h4>{card.title}</h4><p>{card.detail}</p><small>Owner / {card.owner}</small><label>Stage<select value={card.status} onChange={event=>move(card.id,event.target.value)}>{PIPELINE_COLUMNS.map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</select></label></article>)}</section>)}</div></>}
      {section==="transactions" && <div className="site-demo-transactions">{TRANSACTIONS_SEED.map(item=><button key={item.id} onClick={()=>setTransaction(item)}><span><strong>{item.merchant}</strong><small>{item.reference} / {item.date}</small></span><span>{item.status}</span><b>{item.amount} ↗</b></button>)}</div>}
      {section==="disputes" && <div className="site-demo-columns"><div className="site-demo-select-list">{DISPUTES_SEED.map(item=><button key={item.id} aria-pressed={disputeId===item.id} onClick={()=>setDisputeId(item.id)}><strong>{item.customer}</strong><small>{item.reason}</small><span>{item.amount} / {item.status}</span></button>)}</div><section><h3>{dispute.reason}</h3><p>{dispute.customer} / {dispute.amount}</p><h4>Evidence</h4><ul>{dispute.evidence.map(x=><li key={x}>{x}</li>)}</ul><h4>Timeline</h4><ul>{dispute.timeline.map(x=><li key={x}>{x}</li>)}</ul><div className="site-demo-actions"><button disabled>Refund</button><button disabled>Reject</button></div><p className="site-caption">Resolution actions are disabled in this simulation.</p></section></div>}
      {section==="settings" && <div className="site-demo-settings">{SETTINGS_SEED.map(item=><article key={item.id}><div><h3>{item.label}</h3><p>{item.detail}</p></div><strong>{item.value}</strong></article>)}<p className="site-caption">Illustrative policy values. These settings are read-only.</p></div>}
      {section==="audit" && <ol className="site-demo-audit">{AUDIT_LOG.map(item=><li key={item.id}><span className="site-label">{item.time}</span><p>{item.action}</p><small>{item.source} / sample event</small></li>)}</ol>}
    </div></div> : <div className="site-demo-customer"><header><span className="site-label">Customer / Personal workspace</span><h2>Your activity.</h2><p>Only the account’s orders, profile, and notifications are visible here.</p></header><div className="site-demo-columns"><section><h3>Orders</h3><ul className="site-demo-list">{CUSTOMER_ORDERS.map(item=><li key={item.id}><div>{item.label}<small>{item.detail}</small></div><span>{item.status}</span></li>)}</ul></section><section><h3>Notifications</h3><ul className="site-demo-list">{CUSTOMER_NOTIFICATIONS.map(item=><li key={item.id}><div>{item.label}<small>{item.detail}</small></div></li>)}</ul><h3>Account</h3><p>Acme Retail / Growth plan / Monthly billing</p></section></div></div>}
    <div className="site-demo-end"><p>What should an operator be able to control in your product?</p><SignalLink to="/start">Discuss the operational side</SignalLink></div>
    <dialog ref={dialog} aria-label="Fictional transaction detail" className="site-demo-dialog" onCancel={()=>setTransaction(null)} onClick={event=>{if(event.target===event.currentTarget)setTransaction(null);}}>{transaction && <><header><span className="site-label">Fictional transaction / {transaction.reference}</span><button onClick={()=>setTransaction(null)}>Close</button></header><h2>{transaction.amount}</h2><p>{transaction.merchant} / {transaction.method}</p><dl>{transaction.fees.map(fee=><div key={fee.label}><dt>{fee.label}</dt><dd>{fee.value}</dd></div>)}<div><dt>Net deposited</dt><dd>{format(money(transaction.amount)-transaction.fees.reduce((sum,fee)=>sum+money(fee.value),0))}</dd></div></dl></>}</dialog>
  </section>;
}
