# Generated by Django 5.2.4 on 2026-09-24 03:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_contactrequest_qualification"),
    ]

    operations = [
        migrations.CreateModel(
            name="InquiryRateBucket",
            fields=[
                (
                    "key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name="contactrequest",
            name="submission_digest",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="contactrequest",
            name="submission_key",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="InquiryNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("deliveries", models.JSONField(blank=True, default=dict)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                (
                    "next_attempt_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_error", models.CharField(blank=True, max_length=240)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("lease_token", models.UUIDField(editable=False, null=True)),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification",
                        to="leads.contactrequest",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "next_attempt_at"],
                        name="inquiry_delivery_due",
                    )
                ],
            },
        ),
    ]
